[project]
name = "ru-uk-bot"
dynamic = ["version"]
requires-python = ">=3.13,<4"

dependencies = [
    "aiogram>=3.31,<4",
    "pydantic-settings>=2.15,<3",
    "google-cloud-translate>=3,<4",
    "google-cloud-speech>=2,<3",
]

[build-system]
requires = ["setuptools>=80"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["ru_uk_bot*"]

[tool.setuptools.dynamic]
version = {attr = "ru_uk_bot._version.__version__"}
